# This workflow is the minimal Version, similar as the Daniel Schwarz

name: Java Bulid

on:push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3                # ting: ???? need to change??
    - name: Set up JDK 22
      uses: actions/setup-java@v3              # ting: ???? need to change??
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
